services:
  postgres:
    image: postgres:17-alpine
    container_name: supmeal-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: supmeal
      POSTGRES_USER: supmeal
      POSTGRES_PASSWORD: supmeal_developpement

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U supmeal -d supmeal"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./serveur

    container_name: supmeal-backend
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://supmeal:supmeal_developpement@postgres:5432/supmeal?schema=public
      JWT_SECRET: ${JWT_SECRET:-change_me_before_delivery}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      FRONTEND_URL: ${FRONTEND_URL}

    ports:
      - "3000:3000"

    volumes:
      - recipe-uploads:/app/uploads

  frontend:
    build:
      context: ./client

    container_name: supmeal-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "8080:80"

volumes:
  postgres-data:
  recipe-uploads: